version: 2.1
orbs:
  slack: circleci/slack@3.4.0
jobs:
  test:
    executor: vsce/node-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run check
  publish:
    executor: vsce/node-browsers
    steps:
      - checkout
      - run: npx vsce publish -p "$VSCODE_MARKETPLACE_TOKEN"
workflows:
  build:
    jobs:
      - test
  test-publish:
    jobs:
      - test:
          filters:
            branches:
              only: never-release-on-a-branch
            tags:
              only: /v[0-9]+.[0-9]+.[0-9]+/
      - publish:
          context:
            - Tilt VSCE Context
            - Tilt Slack Context
          filters:
            branches:
              only: never-release-on-a-branch
            tags:
              only: /v[0-9]+.[0-9]+.[0-9]+/
          requires:
            - test

